---
- elb_application_lb:
    name: elb-apps
    region: us-east-1
    subnets:
      - subnet-03bec374
      - subnet-ddac3c84
    security_groups: sg-d63f74b2
    scheme: internal
    listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward
            TargetGroupName: mytarget
#        Certificates:
#          - CertificateArn: arn:aws:iam::12345678987:server-certificate/test.domain.com
#        SslPolicy: ELBSecurityPolicy-2015-05
    tags:
        Name: Elb-apps
        Project: Personal
        Environment: POC
        Sponsor: Olabode Osinubi
        CreatedBy: Ansible
    access_logs_enabled: yes
    access_logs_s3_bucket: olabode
    access_logs_s3_prefix: mylogs
    state: present

- ec2_elb_facts:
    names: elb-apps
    region: us-east-1
  register: elblist