---
# elbTarget group tasks
#- import_tasks: targetgroup.yml
#  when: targetgroup == true
- import_tasks: elbapplication.yml
  when: elbapplication == true
#- import_tasks: targetgroup-terminate.yml
#  when: terminatetarget == true
#- import_tasks: elb-appterminate.yml
#  when: terminate-elb == true