---
- hosts: localhost
  tasks:
    - elb_target_group:
        name: "{{ name }}"
        protocol: "{{ protocol }}"
        port: "{{ Port }}"
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        health_check_path: "{{ health_check_path }}"
        successful_response_codes: "{{ successful_response_codes }}"
        targets:
          - Id: "{{ Id }}"
            Port: "{{ Port }}"
          - Id: "{{ Id }}"
            Port: "{{ Port }}"
        tags:
            TargetName: "{{ TargetName }}"
            Project: "{{ Project }}"
            Environment: "{{ Environment }}"
            Sponsor: "{{ Sponsor }}"
            CreatedBy: "{{ CreatedBy }}"
        state: "{{ state }}"
          
    - elb_application_lb:
        name: "{{ name }}"
        region: "{{ region }}"
        subnets: "{{ subnets }}"
        security_groups: "{{ security_groups }}"
        scheme: "{{ scheme }}"
        listeners:
          - Protocol: "{{ Protocol }}"
            Port: "{{ Port }}"
            DefaultActions:
              - Type: "{{ Type }}"
                TargetGroupName: "{{ TargetGroupName }}"
#            Certificates:
#              - CertificateArn: arn:aws:iam::12345678987:server-certificate/test.domain.com
#            SslPolicy: ELBSecurityPolicy-2015-05
            # Rules:
              # - Conditions:
                  # - Field: "{{ Field }}"
                    # Values: "{{ Values }}"
                # Priority: "{{ Priority }}"
                # Actions:
                  # - TargetGroupName: "{{ TargetGroupName }}"
                    # Type: "{{ Type }}"
        tags:
            ELBName: "{{ ELBName }}"
            Proj: "{{ Proj }}"
            Env: :{{ Env }}"
            Sponse: "{{ Sponse }}"
            BuildBy: "{{ BuildBy }}"
        access_logs_enabled: "{{ access_logs_enabled }}"
        access_logs_s3_bucket: "{{ access_logs_s3_bucket }}"
        access_logs_s3_prefix: "{{ access_logs_s3_prefix }}"
        state: "{{ state }}"
                    
    - ec2_elb_facts:
        names: "{{ elbname) }}"
        region: "{{ region }}"
      register: "{{ register }}"    