---
- hosts: localhost
  tasks:
    - elb_target:
        target_group_name: mytarget
        region: us-east-1
        target_id: i-0ad9d8e2e05278b82
        deregister_unused: yes
        target_port: 80
        state: absent