---
- hosts: mytarget
  tasks:
    - elb_target:
        target_group_name: mytarget
        region: us-east-1
        target_id: i-0e53a36a464471866
#        deregister_unused: yes
        target_port: 80
        state: present
