---
- hosts: localhost
  tasks:
    - name: Create EC2 instances
      ec2:
        key_name: "{{ key_name }}" 
        instance_type: "{{ instance_type }}" 
        image: "{{ image }}" 
        region: "{{ region }}" 
        group_id: "{{ group_id }}"
        wait: "{{ wait }}" 
        instance_tags:
          application: "{{ application }}" 
        exact_count: "{{ exact_count }}" 
        count_tag:
          application: "{{ application }}" 
        instance_tags: 
          Name: "{{ Name }}" 
          Sponsor: "{{ Sponsor }}" 
          BuiltBy: "{{ BuiltBy }}" 
          ManagedBy: "{{ ManagedBy }}"          
      register: "{{ register }}" 
      when: instance == true
        