---
# Rhel Postvalidation Process
# uncomment the local_action: if you are running this playbook on cli.
#- name: Creates Directory
#  file: path=/home/postvalidation state=directory

#- action: ping 

#- name: Server Uptime
#  shell: echo $(hostname) for $(date);uptime > {{post_uptime_log}}

#- name: Server Uptime
#  shell: echo $(hostname) for $(date);uptime
#  register: ps

#- debug: var=ps.stdout_lines
#- action: copy content={{ ps.stdout_lines }} dest={{local_post_uptime_log}}

#- name: OS Version
#  shell: echo $(hostname) for $(date);cat /etc/redhat-release > {{post_version_log}}
#  become: true

#- name: OS Version
#  shell: echo $(hostname) for $(date);cat /etc/redhat-release
#  register: ps
#  become: true

#- debug: var=ps.stdout_lines

#- name: clean all yum caches
#  shell: echo $(hostname) for $(date);yum clean all
#  register: ps

#- debug: var=ps.stdout_lines
         
#- name: Kernel Version
#  shell: echo $(hostname) for $(date);uname -r > {{post_kernel_log}}

#- name: Kernel Version
#  shell: echo $(hostname) for $(date);uname -r
#  register: ps

#- debug: var=ps.stdout_lines
#- local_action: copy content={{ ps.stdout_lines }} dest={{local_post_kernel_log}}
    
#- name: Checking Network Interface
#  shell: echo $(hostname) for $(date);ifconfig -a > {{post_interface_log}}

#- name: Checking Network Interface
#  shell: echo $(hostname) for $(date);ifconfig -a
#  register: ps

#- debug: var=ps.stdout_lines
#- local_action: copy content={{ ps.stdout_lines }} dest={{local_post_interface_log}}

#- name: Routing Point
#  shell: echo $(hostname) for $(date);route -n > {{post_route_log}}

#- name: Routing Point
#  shell: echo $(hostname) for $(date);route -n
#  register: ps

#- debug: var=ps.stdout_lines
#- local_action: copy content={{ ps.stdout_lines }} dest={{local_post_route_log}}

#- name: Check Memory and Swap Resources
#  shell: echo $(hostname) for $(date);free -h > {{post_mem_swap_log}}

#- name: Check Memory and Swap Resources
#  shell: echo $(hostname) for $(date);free -h
#  register: ps

#- debug: var=ps.stdout_lines
#- local_action: copy content={{ ps.stdout_lines }} dest={{local_post_mem_swap_log}}

#- name: Check Filesystems and Sizes
#  shell: echo $(hostname) for $(date);df -h > {{post_file_system_log}}

#- name: Check Filesystems and Sizes
#  shell: echo $(hostname) for $(date);df -h
#  register: ps

#- debug: var=ps.stdout_lines
#- local_action: copy content={{ ps.stdout_lines }} dest={{local_post_file_system_log}}

#- name: Check Updates (yum)
#  shell: echo $(hostname) for $(date);yum check-update > {{post_update_check_log}} || test $? -eq 100

#- name: Check Updates (yum)
#  shell: echo $(hostname) for $(date);yum check-update || test $? -eq 100
#  register: yumoutput

#- debug: var=yumoutput.stdout_lines
#- local_action: copy content={{ yumoutput.stdout_lines }} dest={{local_post_update_check_log}}
    
#- name: Fstab Contents File
#  shell: echo $(hostname) for $(date);cat /etc/fstab > {{post_fstab_content_log}}
#  become: true

#- name: Fstab Contents File
#  shell: echo $(hostname) for $(date);cat /etc/fstab
#  register: ps
#  become: true

#- debug: var=ps.stdout_lines
#- local_action: copy content={{ ps.stdout_lines }} dest={{local_post_fstab_content_log}}

#- name: Mount Point
#  shell: echo $(hostname) for $(date);mount > {{post_mount_log}}

#- name: Mount Point
#  shell: echo $(hostname) for $(date);mount
#  register: ps

#- debug: var=ps.stdout_lines

#- name: Java Version
#  shell: echo $(hostname) for $(date);java -version > {{post_javaversion_log}}

#- name: Java Version
#  shell: echo $(hostname) for $(date);java -version 2>&1
#  register: ps

#- debug: var=ps.stdout_lines
#- local_action: copy content={{ ps.stdout_lines }} dest={{local_post_mount_log}}

#- name: Creates Directory
#  file: path=/mnt/nfs/var/nfsshare/diffvalidation state=directory

#- name: Creates Diff-Dir
#  file: path=/home/diffdir state=directory

- name: OS version Diff1
  shell: echo $(hostname) for $(date);grep "CentOS Linux release" {{version_log}} > /home/diffdir/version.tmp.log

- name: OS Version Diff2
  shell: echo $(hostname) for $(date);grep "CentOS Linux release" {{post_version_log}} > /home/diffdir/versionp.tmp.log

- name: OS Version Diff
  shell: echo $(hostname) for $(date);diff -p /home/diffdir/version.tmp.log /home/diffdir/versionp.tmp.log >> /mnt/nfs/var/nfsshare/diffvalidation/versiondiff.log

#- name: Remove files
#  shell: rm /home/prevalidation/*.tmp.log;rm /home/postvalidation/*.tmp.log

