---
# Rhel Postvalidation Process
- name: Creates Directory
  file: path=/mnt/nfs/var/nfsshare/prevalidation state=directory

- action: ping 

- name: Java Version
  shell: echo $(hostname) >> {{javaversion_log}};echo $(hostname) for $(date);java -version >> {{javaversion_log}}

- name: Java Version
  shell: echo $(hostname) for $(date);java -version 2>&1
  register: ps

- debug: var=ps.stdout_lines

- name: Server Uptime
  shell: echo $(hostname) >> {{uptime_log}};echo $(hostname) for $(date);uptime >> {{uptime_log}}

- name: Server Uptime
  shell: echo $(hostname) for $(date);uptime
  register: ps

- debug: var=ps.stdout_lines
 
#- name: Routing Point
#  shell: echo $(hostname) for $(date);route -n > {{route_log}}

#- name: Routing Point
#  shell: echo $(hostname) for $(date);route -n 
#  register: ps

#- debug: var=ps.stdout_lines                   

- name: OS Version
  shell: echo $(hostname) for $(date);cat /etc/redhat-release >> {{version_log}}
  become: true

- name: OS Version
  shell: echo $(hostname) for $(date);cat /etc/redhat-release 
  register: ps
  become: true

- debug: var=ps.stdout_lines

- name: Check Memory and Swap Resources
  shell: echo $(hostname) for $(date);free -h >> {{mem_swap_log}}

- name: Check Memory and Swap Resources
  shell: echo $(hostname) for $(date);free -h
  register: ps

- debug: var=ps.stdout_lines

- name: Free Disk space
  shell: echo $(hostname) for $(date);df -Pl|grep '^/dev'|awk '{print $6, 100 - $5}'|sed 's/%//' >> {{free_disk_log}}

- name: Free Disk space
  shell: echo $(hostname) for $(date);df -Pl|grep '^/dev'|awk '{print $6, 100 - $5}'|sed 's/%//'
  register: ps

- debug: var=ps.stdout_lines

- name: Used Disk space
  shell: echo $(hostname) for $(date);df -h | grep -vE 'Filesystem|tmpfs|boot' | awk '{print $4 " " $5}' | while read output; do   echo $output;   usep=$(echo $output | awk '{ print $1}' | cut -d'%' -f1  );   partition=$(echo $output | awk '{ print $2 }' );   if [ "$usep" -ge "85" ]; then     echo "Running out of space \"$partition ($usep%)\" on $(hostname) as on $(date)" | mailx -s Alert_Space  hcqis-ops-middleware@hcqis.org hcqis-ops-dba@hcqis.org;  fi; done >> {{used_disk_log}}

- name: Used Disk space
  shell: echo $(hostname) for $(date);df -h | grep -vE 'Filesystem|tmpfs|boot' | awk '{print $4 " " $5}' | while read output; do   echo $output;   usep=$(echo $output | awk '{ print $1}' | cut -d'%' -f1  );   partition=$(echo $output | awk '{ print $2 }' );   if [ "$usep" -ge "85" ]; then     echo "Running out of space \"$partition ($usep%)\" on $(hostname) as on $(date)" | mailx -s Alert_Space  hcqis-ops-middleware@hcqis.org hcqis-ops-dba@hcqis.org;  fi; done
  register: ps

- debug: var=ps.stdout_lines

- name: Check Filesystems and Sizes
  shell: echo $(hostname) for $(date);df -h >> {{file_system_log}}

- name: Check Filesystems and Sizes
  shell: echo $(hostname) for $(date);df -h
  register: ps    

- debug: var=ps.stdout_lines

- name: Fstab Contents File
  shell: echo $(hostname) for $(date);cat /etc/fstab >> {{fstab_content_log}}
  become: true

- name: Fstab Contents File
  shell: echo $(hostname) for $(date);cat /etc/fstab
  register: ps
  become: true

- debug: var=ps.stdout_lines

- name: Mount Point
  shell: echo $(hostname) for $(date);mount >> {{mount_log}}

- name: Mount Point
  shell: echo $(hostname) for $(date);mount
  register: ps

- debug: var=ps.stdout_lines

- name: Kernel Version
  shell: echo $(hostname) for $(date);uname -r >> {{kernel_log}}

- name: Kernel Version
  shell: echo $(hostname) for $(date);uname -r
  register: ps

- debug: var=ps.stdout_lines

- name: Check Updates (yum)
  shell: echo $(hostname) for $(date);yum check-update >> {{update_check_log}} || test $? -eq 100

- name: Check Updates (yum)
  shell: echo $(hostname) for $(date);yum check-update || test $? -eq 100
  register: yumoutput

- debug: var=yumoutput.stdout_lines

- name: Check Last Yum Command Run,  Start , End Date and Installed Packages
  shell: echo $(hostname) for $(date);yum history info | grep -e "Begin time" -e "Command Line" -e "Installed" -e "User" >> {{last_yumrun_log}}

- name: Check Last Yum Command Run,  Start , End Date and Installed Packages
  shell: echo $(hostname) for $(date);yum history info | grep -e "Begin time" -e "Command Line" -e "Installed" -e "User"
  register: last_yum_command

- debug: var=last_yum_command.stdout_lines

- name: clean all yum caches
  shell: echo $(hostname) for $(date);yum clean all
  register: ps

- debug: var=ps.stdout_lines
