---
#- name: Target group play
- elb_target_group:
    name: mytarget
    protocol: http
    port: 1080
    vpc_id: vpc-08a1816d
    region: us-east-1
    health_check_path: /
    successful_response_codes: 200
    targets:
      - Id: i-08437d4eff1c2f6cb
        Port: 80
      - Id: i-0ecad15ec7a9fb305
        Port: 80
    tags:
        Name: mytarget
        Project: Oshie
        Environment: POC
        Sponsor: Olabode Osinubi
        CreatedBy: Olabode Osinubi
    state: present
