---
- elb_target_group:
    name: Newtarget3
    protocol: http
    port: 88
    vpc_id: vpc-08a1816d
    region: us-east-1
    health_check_path: /
    successful_response_codes: "200,250-260"
    target_type: instance
    targets:
      - Id: i-0c8980f76c4db99da
        Port: 80
      - Id: i-0c091d22ddf88270d
        Port: 80
    tags:
        Name: Newtarget3
        Project: Oshie
        Environment: POC
        Sponsor: Olabode Osinubi
        CreatedBy: "Ansible"
    state: present
